version: '3.8'

services:
  postgres:
    image: harbor.narvanventures.com/dockerhub/postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  starrocks:
    image: harbor.narvanventures.com/dockerhub/starrocks/allin1-ubuntu:latest
    container_name: starrocks
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9030:9030"    # MySQL FE
      - "8030:8030"    # Web UI/HTTP
    volumes:
      - ./starrocks_data:/opt/starrocks
    healthcheck:
      test: ["CMD", "mysql", "-h", "127.0.0.1", "-P", "9030", "-uroot", "-e", "SHOW DATABASES;"]
      interval: 10s
      timeout: 5s
      retries: 10

  jobmanager:
    image: harbor.narvanventures.com/dockerhub/flink:1.17-scala_2.12
    container_name: jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
    volumes:
      - ./flink_libs:/opt/flink/lib-extra
      - ./sql:/opt/flink/sql
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    depends_on:
      - starrocks

  taskmanager:
    image: harbor.narvanventures.com/dockerhub/flink:1.17-scala_2.12
    container_name: taskmanager
    command: taskmanager
    volumes:
      - ./flink_libs:/opt/flink/lib-extra
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    depends_on:
      - jobmanager

volumes:
  pg_data:
  starrocks_data:
